### ISSUE TITLE
pass a variable through params (redux store)

### ISSUE THREAD

**Issue by AgentChris** [TehShrike/riot-state-renderer#10]
Hey man! great tool for riot, I have a question though how can i pass let's say a variable(in my case a redux store) on a component in the parameters, I've tried to pass it in the activate function but this doesn't resolve my problem because riot on mount event won't have the params.

**Comment by TehShrike** [comment]
I actually wanted to start using Redux myself (with abstract-state-router and Ractive), so I made [state-router-redux-ractive](https://github.com/TehShrike/state-router-redux-ractive).

You can see an example implementation in the [ractive-redux folder of state-router-examples](https://github.com/TehShrike/state-router-example/tree/gh-pages/implementations/ractive-redux).  In [topics.js](https://github.com/TehShrike/state-router-example/blob/gh-pages/implementations/ractive-redux/app/topics/topics.js#L89-L94) you can see it in action - when creating a state, you can pass in `initialState`, `reducer`, and `afterAction`.  state-router-redux-ractive does everything else.

It wouldn't take much to refactor out the code that makes that module Ractive-specific.
1. the event methods (`on` and `fire`, in Ractive's case) would need to be configurable
2. an `applyDataToTemplate` method would need to be passed in - it would need to take the domApi, the last state, and the current state.  The Ractive implementation would pass in a function containing [these lines](https://github.com/TehShrike/state-router-redux-ractive/blob/master/index.js#L52-L53).  The Riot implementation would be something like `tag.opts = newState; tag.update()`

Any thoughts?  Does that look like something you'd be interested in using with Riot?

**Comment by TehShrike** [comment]
@AgentChris or put another way, if I altered state-router-redux-ractive so you could use Redux with Riot, would you use it? :-)

**Comment by TehShrike** [comment]
Closed in favor of https://github.com/TehShrike/state-router-redux-ractive/issues/1

This is a thing I'd like to make.  Let me know if you'd be willing to use it @AgentChris.
