### ISSUE TITLE
notfound implementation

### ISSUE THREAD

**Issue by AgentChris** [TehShrike/riot-state-renderer#11]
hey man, great router. But i have a problem implementing the "not found" feature.

can you give an example?

-there are some problems with the backbutton
-i can't not load a riot tag if the route is not valid, because the route object is needed, if put no route it will redirect me to "/" instead of "/does_not_exist_route"

**Comment by TehShrike** [comment]
Looks like you made some good comments over at https://github.com/TehShrike/abstract-state-router/issues/63#issuecomment-230085702, I'll close this issue and reply over at that one!
