### ISSUE TITLE
Nested templates not loaded properly

### ISSUE THREAD

**Issue by Matzu89** [TehShrike/riot-state-renderer#6]
This afternoon I experienced a bug while implementing nested routing: the riot-tag attribute on the ui-view tag did not get updated. While my template was rendered, styling broke and I found out it was because the riot-tag didn't get updated. I will commit a fix for this asap.

**Comment by TehShrike** [comment]
Fixed by 6b09b3f81b4b024abcf03a9a92b8c502ce10989e
