### ISSUE TITLE
Duplicate events triggered when switching between same routes

### ISSUE THREAD

**Issue by osiloke** [TehShrike/riot-state-renderer#8]
I noticed that navigating between the same state creates multiple tags in memory. You can see this behaviour if you listen to the `unmount` event from the activate method of a state.
i.e

```
stateRouter.addState({
route: ':name'
...
activate: (context) =>{

   tag.on('unmount', () => console.log(`unmounting ${context.parameters.name}`))
}
```

If you switch between maybe `/luigi` and `/mario` n times and then switch to a new state, you will see that the last state gets unmounted n times. Please let me know if i'm missing something
For now, i'm assuming this is because the events are added everytime the state is activated.

My workaround is to do a little clean up when the `reset` event is triggered.
i.e

```
tag.on('reset', () => { 
   tag.off('reset unmount mount')
 })
```

**Comment by TehShrike** [comment]
So the idea is that on a state change, if the template would be the same, the abstract-state-renderer doesn't destroy the whole template/tag, it only clears it out for the next state, to reduce the number of DOM nodes that have to be created.

By the parlance of the abstract-state-router, switching between `/luigi` and `/mario` causes that state template to "change" - as opposed to being "destroyed" and then a new template being "created" (those are the [three things that can happen on a state transition](https://github.com/TehShrike/abstract-state-router#every-state-change-does-this-to-states)).

Obviously, what happens to the template on a change varies between rendering implementations.  RactiveJS actually has a `reset` method, so in the ractive renderer, I just [call that directly](https://github.com/TehShrike/ractive-state-router/blob/master/render.js#L44).

RiotJS doesn't have a way to reset the tag, so what I do there is:
1. emit a "reset" event for the benefit of the code written directly into the tag
2. overwrite the tag options with the content that was returned by the resolve for the new state
3. call `update` to cause the tag to refresh

You can see that code here: https://github.com/TehShrike/riot-state-renderer/blob/master/index.js#L43-L45

**So, here's what's happening in your case:**

Every single state transition between the same state is going to cause a new `unmount` listener to be added to the exact same tag object when the `activate` function is called.  To save on DOM interactions, that tag won't get destroyed until it absolutely needs to be.

In your case, you shouldn't use the tag to get your notion of when a state disappears - the `reset` event is there for the code you write directly in your tag, but inside that activate function it would be more correct to listen to the [destroy event](https://github.com/TehShrike/abstract-state-router#context-events) (yeah, it is kind of buried there in the middle of the docs, and it's not really explained - I need to improve that).

When that event is fired on the context object, that is the signal that the state is going away and you should clean up any event listeners or anything asynchronous you may have going on.

If you write code in the tag, it will have to listen for the reset event - but I think ideally you wouldn't have any code in there doing anything that would need much cleaning up anyway, I would probably put that code that interacts with the rest of the system inside the activate function.

Does that all make sense?  Other than the poor documentation of the destroy event, do you see anything else I might have missed?

**Comment by osiloke** [comment]
When you mention `directly in a tag`, are you referring to the template (riot tag) passed to the state? 
So, i tried to listen to the destroy event in the activate method but it doesn't seem to get triggered unless there is a separate eventbus for staterouter. 
i.e

```
tag = context.domApi
tag.on('destroy', () => {
        console.log('destroy '+schema_name)
        tag.off('reset unmount mount')
        RiotControl.off(`entity:${schema_name}_changed`)
      })
tag.on('reset', () => {
        console.log('reset '+schema_name) 
      })
```

That is why i listened to the reset event which is triggered and i can at least cleanup the last listeners as i showed in my tiny snippet above.

**Comment by TehShrike** [comment]
Correct, the `reset` event is there for the benefit of the code inside of your Riot template.  The abstract-state-renderer uses the context object to let states know about events.

The abstract-state-router doesn't assume that the renderer comes with any sort of event bus - so, the context event passed to the activate function is an [EventEmitter](https://iojs.org/api/events.html#events_class_events_eventemitter).

``` js
context.on('destroy', () => {
    // the Riot-renderer-specific "reset" event is being emitted in the tag at about this same time
})
```

**Comment by TehShrike** [comment]
@osiloke has the `destroy` event on the context object been working for you?

I wonder if it would be clearer to support the activate function returning event listener functions, like Ractive decorators do, so you could do something like

``` js
activate: function(context) {
    // ...

    return {
        destroy: () => {
            console.log('context destroyed', schema_name)
        }
    }
}

```

**Comment by osiloke** [comment]
Sorry for not getting back earlier, i was not listening on the context object. Giving this new info, it should work now. I was a bit confused about how asr passes events to riot tags.

**Comment by TehShrike** [comment]
I tried to improve the abstract-state-router docs a bit to prevent this kind of misunderstanding.  Hopefully this makes it a bit clearer for others: https://github.com/TehShrike/abstract-state-router/commit/bd09239fec4a2b1865e83084e4d614751fa59b7e
